### ISSUE TITLE
& is not replaced using Innovator 11sp15

### ISSUE THREAD

**Issue by rpmengel** [ArasLabs/project-template-migration#1]
When running the action in Innovator 11sp15 the result contains special characters that are not being replaced.  
& did not get replaced with &amp;

In the Method **GetProjectTemplateAML** / function **_escapeChars_** the replacement code is correct but the _CurrChild.text_ seems to be readonly.  The & was replaced in the local variable but not in _currChild.text._

![replacetext](https://user-images.githubusercontent.com/25620055/52358275-b61bf780-2a05-11e9-89e8-508afb7d13c5.png)

**Comment by cgillis-aras** [comment]
This is fixed in 2f0c9eabaae5ac35f0a7c837a358d98a2a66be53. We changed the reference from _currChild.text_ to _currChild.textContent_.

**Comment by EliJDonahue** [comment]
Fix was confirmed in release v3.1. Closing out this issue.
